export const FETCH_STATS_LADDSTATION_SWE = 'FETCH_STATS_LADDSTATION_SWE';
export const FETCH_STATS_LADDSTATION_SWE_FULFILLED = 'FETCH_STATS_LADDSTATION_SWE_FULFILLED';
export const FETCH_STATS_LADDSTATION_SWE_REJECTED = 'FETCH_STATS_LADDSTATION_SWE_REJECTED';
export const FETCH_STATS_LADDSTATION_NOR = 'FETCH_STATS_LADDSTATION_NOR';
export const FETCH_STATS_LADDSTATION_NOR_FULFILLED = 'FETCH_STATS_LADDSTATION_NOR_FULFILLED';
export const FETCH_STATS_LADDSTATION_NOR_REJECTED = 'FETCH_STATS_LADDSTATION_NOR_REJECTED';
